最終審査会の動画と受賞者を掲載
codeforjapan/ccc2022-website pull request #8
Opened 2022-09-30 17:27 UTC by kota-yata

<img width="1920" alt="Screen Shot 2022-10-01 at 2 25 59" src="https://user-images.githubusercontent.com/51294895/193324256-6617c0cd-4ff7-468f-890c-2d2a02f0611f.png">

動画表示部分に関してはreact-youtubeの仕様変更に伴うちょっとした変更を除いては去年と同じ
主にIndexFinalWinnersの部分を新しく書いているのでChakraの書き方とかNextの作法みたいなところのチェックお願いできるとありがたい

2022-09-30 17:28 UTC, kota-yata commented
一応レスポンシブ対応済み（Devtoolsで調整済み）

2022-10-01 01:20 UTC, MaySoMusician requested changes
いくつか要変更点を出しました

あと `react-youtube` がインストールされてなさそうなので追加してほしいのと、 `components/FinalWinnerCard.tsx` は不要であればファイルを削除してください（ビルドエラーになるため）

`yarn dev` のほかに `yarn build` でビルドが通るかも確認しておいてください（この場合 `yarn start` でサーバーを起動させて生成物を確認可能）

2022-10-01 01:20 UTC, MaySoMusician commented on components/IndexFinalWinners.tsx
> +              flex
flexプロパティはCSSのflexと同じ形式で値を指定する必要があります。

`"1 1 33.3%"` とか `"1 0 33.3%"` とかになると思います
cf: https://developer.mozilla.org/ja/docs/Web/CSS/flex

2022-10-01 01:20 UTC, MaySoMusician commented on components/IndexFinalWinners.tsx
> +              <Text fontSize="1xl" whiteSpace="nowrap" margin="0 auto">
```suggestion
              <Text fontSize="xl" whiteSpace="nowrap" margin="0 auto">
```
`1xl` というキーワードは無さそうです

2022-10-01 01:20 UTC, MaySoMusician commented on styles/FinalWinners.module.scss
>    }
ulとliのスタイルは使ってなさそうなので消して大丈夫です

2022-10-01 01:20 UTC, MaySoMusician commented on styles/FinalWinners.module.scss
> +  // }
```suggestion
```
ここも使ってないのであれば消してOKです

2022-10-01 01:20 UTC, MaySoMusician commented on styles/FinalWinners.module.scss
> +    position: relative;
IndexFinalWinners.tsxで指定している `whiteSpace="nowrap" margin="0 auto"` もCSSで書いたほうが、CSS指定の記述場所が統一できるのでいいかも

その場合 `p:first-child` ではなく `&AwardName` とかでクラス名をつけて、 フロントからは `className={styles.FinalWinnersAwardName}` とかで明示的に指定したほうがわかりやすい

2022-10-05 13:42 UTC, kota-yata commented on components/IndexFinalWinners.tsx
> +              flex
必要ない記述だったので削除済み

2022-10-05 13:44 UTC, kota-yata commented on styles/FinalWinners.module.scss
>    }
削除済み

2022-10-08 09:20 UTC, kota-yata commented
Fork先でデプロイして確認したところ正常に動作したので一旦マージします

2022-10-08 09:20 UTC, merged